"""empty message

Revision ID: 48479d09803f
Revises: 091a537abefe
Create Date: 2019-04-11 22:10:57.931755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48479d09803f'
down_revision = '091a537abefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
