"""empty message

Revision ID: dfbacdb0f63b
Revises: 40e966a0107f
Create Date: 2019-04-12 17:54:55.873471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfbacdb0f63b'
down_revision = '40e966a0107f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'description')
    # ### end Alembic commands ###
